server:
  port: 8787

spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      file-size-threshold: 10MB

video:
  ffmpeg-path: ./ffmpeg/ffmpeg.exe
  ffprobe-path: ./ffmpeg/ffprobe.exe
  input-dir: E:/照片
  output-dir: E:/压缩图片
  backup-dir: ./data/backup
  temp-dir: ./data/temp
  log-dir: ./data/logs
  db-path: ./data/db/video-compressor.db
  allowed-extensions:
    - mp4
    - mov
    - m4v
    - mkv
    - avi
    - 3gp
  default-min-size-mb: 10
  max-parallel-tasks: 1
